CREATE DATABASE COP4331_SLP19;

CREATE TABLE COP4331_SLP19.Users (
    DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    DateLastLoggedIn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    FullName VARCHAR(50) NOT NULL DEFAULT '' ,
    Pass VARCHAR(255) NOT NULL DEFAULT '' ,
    Email VARCHAR(50) NOT NULL DEFAULT '' ,
    PRIMARY KEY (Email)
);

CREATE TABLE COP4331_SLP19.Contacts (
    LinkID INT NOT NULL AUTO_INCREMENT ,
    SourceUserEmail VARCHAR(50) NOT NULL DEFAULT '' ,
    ContactUsername VARCHAR(50) NOT NULL DEFAULT '' ,
    ContactFirstName VARCHAR(50) NOT NULL DEFAULT '',
    ContactLastName VARCHAR(50) NOT NULL DEFAULT '',
    ContactEmail VARCHAR(50) NOT NULL DEFAULT '' ,
    ContactPhone VARCHAR(50) NOT NULL DEFAULT '' ,
    PRIMARY KEY (LinkID)
);
